name: Update Web Files

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: main  # 要修改的分支名称
      
      - name: 检查文件是否存在
        run: |
          # 检查 HTML 文件
          for file in index.html watch.html about.html; do
            if [ -f "$file" ]; then
              echo "$file 文件存在，继续处理"
            else
              echo "警告：找不到 $file 文件，将跳过对此文件的修改"
              touch "skip_${file//\//_}"  # 使用下划线替换斜杠，避免文件名问题
            fi
          done
          
          # 检查 JS 文件
          for file in js/index-page.js js/douban.js js/player.js js/config.js js/app.js; do
            if [ -f "$file" ]; then
              echo "$file 文件存在，继续处理"
            else
              echo "警告：找不到 $file 文件，将跳过对此文件的修改"
              touch "skip_${file//\//_}"
            fi
          done
      
      - name: 修改 index.html 文件
        if: "!contains(needs.*.outputs.*, 'skip_index.html')"
        run: |
          # 使用 sed 命令修改指定行
          sed -i '6s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '7s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '8s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '9s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '192s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '192s/2023/2025/' index.html
          sed -i '300s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '300s|https://libretv.is-an.org|https://www.zgdy.cn|' index.html
          sed -i '302s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '302s|https://libretv.is-an.org|https://www.zgdy.cn|' index.html
          sed -i '358s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '361s/LibreTV/中国电影ZGDY.CN/' index.html
          sed -i '396s/LibreTV/中国电影/' index.html
          sed -i '397s|https://libretv.is-an.org|https://www.zgdy.cn|' index.html
          sed -i '401s|https://libretv.is-an.org|https://www.zgdy.cn|' index.html
      
      - name: 修改 watch.html 文件
        if: "!contains(needs.*.outputs.*, 'skip_watch.html')"
        run: |
          sed -i '18s/LibreTV/中国电影ZGDY.CN/' watch.html
      
      - name: 修改 about.html 文件
        if: "!contains(needs.*.outputs.*, 'skip_about.html')"
        run: |
          # 修改指定行
          sed -i '6s/LibreTV/中国电影ZGDY.CN/' about.html
          sed -i '23s/LibreTV/中国电影ZGDY.CN/' about.html
          sed -i '27s/LibreTV/中国电影ZGDY.CN/' about.html
          sed -i '45s/LibreTV/中国电影ZGDY.CN/' about.html
          sed -i '49s/LibreTV/中国电影ZGDY.CN/' about.html
          sed -i '75s/LibreTV/中国电影ZGDY.CN/' about.html
          sed -i '105s/LibreTV/中国电影ZGDY.CN/' about.html
          sed -i '151s/LibreTV/中国电影ZGDY.CN/' about.html
          sed -i '153s/LibreTV/中国电影ZGDY.CN/' about.html
      
      - name: 修改 js/index-page.js 文件
        if: "!contains(needs.*.outputs.*, 'skip_js_index-page.js')"
        run: |
          sed -i '48s/LibreTV/中国电影ZGDY.CN/' js/index-page.js
          sed -i '72s/LibreTV/中国电影ZGDY.CN/' js/index-page.js
      
      - name: 修改 js/douban.js 文件
        if: "!contains(needs.*.outputs.*, 'skip_js_douban.js')"
        run: |
          sed -i '240s/LibreTV/中国电影ZGDY.CN/' js/douban.js
          sed -i '244s/LibreTV/中国电影ZGDY.CN/' js/douban.js
      
      - name: 修改 js/player.js 文件
        if: "!contains(needs.*.outputs.*, 'skip_js_player.js')"
        run: |
          sed -i '221s/LibreTV/中国电影ZGDY.CN/' js/player.js
      
      - name: 修改 js/app.js 文件
        if: "!contains(needs.*.outputs.*, 'skip_js_app.js')"
        run: |
          for line in 599 603 713 717; do
            sed -i "${line}s/LibreTV/中国电影ZGDY.CN/" js/app.js
          done
      
      - name: 修改 js/config.js 文件
        if: "!contains(needs.*.outputs.*, 'skip_js_config.js')"
        run: |
          sed -i '16s/LibreTV/中国电影/' js/config.js
          sed -i '16s|https://libretv.is-an.org|https://www.zgdy.cn|' js/config.js
          # 修改第6行为指定内容
          sed -i '6c\if (localStorage.getItem('\''doubanEnabled'\'') === null) { localStorage.setItem('\''doubanEnabled'\'','\'true\''); }' js/config.js
      
      - name: 提交修改
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # 添加所有修改过的文件
          for file in index.html watch.html about.html js/index-page.js js/douban.js js/player.js js/config.js js/app.js; do
            if [ -f "$file" ]; then
              git add "$file"
            fi
          done
          
          # 只有当有修改时才提交
          if ! git diff --staged --quiet; then
            git commit -m "Update web files: Replace branding and update config"
            git push
          else
            echo "没有检测到文件修改，跳过提交"
          fi
